import fs from 'fs/promises';
import path from 'path';

/**
 * Saves a generated skill to the .claude/skills directory
 */
export async function saveSkill(skill, workspaceRoot, context) {
  const logger = context?.logger || {
    info: (msg) => console.log(msg),
    error: (msg) => console.error(msg)
  };
  
  try {
    // Create .claude/skills directory if it doesn't exist
    const skillsDir = path.join(workspaceRoot, '.claude', 'skills');
    await fs.mkdir(skillsDir, { recursive: true });
    
    // Create category subdirectory
    const categoryDir = path.join(skillsDir, skill.category || 'general');
    await fs.mkdir(categoryDir, { recursive: true });
    
    // Generate skill file name
    const skillFileName = `${skill.name}.md`;
    const skillFilePath = path.join(categoryDir, skillFileName);
    
    // Generate skill content in markdown format
    const skillContent = generateSkillMarkdown(skill);
    
    // Write skill file
    await fs.writeFile(skillFilePath, skillContent, 'utf-8');
    
    logger.info(`  ✓ Saved skill: ${skillFilePath}`);
    
    return skillFilePath;
  } catch (error) {
    logger.error(`Error saving skill ${skill.name}: ${error.message}`);
    throw error;
  }
}

/**
 * Generates markdown content for a skill in Agent Skills format
 * with YAML frontmatter
 */
function generateSkillMarkdown(skill) {
  // YAML frontmatter
  const frontmatter = {
    name: skill.name,
    displayName: skill.displayName,
    description: skill.description || '',
    category: skill.category || 'general',
    ...(skill.techStack && skill.techStack.length > 0 && { techStack: skill.techStack }),
    ...(skill.metadata && { metadata: skill.metadata })
  };
  
  // Convert frontmatter to YAML string
  let yaml = '---\n';
  for (const [key, value] of Object.entries(frontmatter)) {
    if (value !== undefined && value !== null) {
      if (Array.isArray(value)) {
        yaml += `${key}:\n`;
        for (const item of value) {
          yaml += `  - ${item}\n`;
        }
      } else if (typeof value === 'object') {
        yaml += `${key}:\n`;
        for (const [subKey, subValue] of Object.entries(value)) {
          if (Array.isArray(subValue)) {
            yaml += `  ${subKey}:\n`;
            for (const item of subValue) {
              yaml += `    - ${item}\n`;
            }
          } else {
            yaml += `  ${subKey}: ${subValue}\n`;
          }
        }
      } else {
        yaml += `${key}: ${value}\n`;
      }
    }
  }
  yaml += '---\n\n';
  
  // Markdown content
  let content = yaml;
  content += `# ${skill.displayName}\n\n`;
  
  if (skill.description) {
    content += `${skill.description}\n\n`;
  }
  
  content += `## Guidelines\n\n`;
  
  for (const guideline of skill.guidelines) {
    content += `- ${guideline}\n`;
  }
  
  content += `\n---\n\n`;
  content += `*Generated by Skill Generator Plugin*\n`;
  
  return content;
}
